# Generated by Django 4.2.5 on 2023-09-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(default=None, max_length=255, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('A', 'All'), ('F', 'Favorite')], default='A', max_length=2),
        ),
    ]
