# Generated by Django 4.2.4 on 2023-08-07 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimg', models.ImageField(default='default.png', upload_to='profile_images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('C', 'Common'), ('F', 'Favorite')], default='C', max_length=2),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_at'], name='notes_note_created_067654_idx'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.participant'),
        ),
    ]
