# Generated by Django 4.2.5 on 2023-09-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_participant_email_alter_note_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email_token',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
