# Generated by Django 4.2.5 on 2024-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_participant_email_token_participant_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('A', 'All'), ('F', 'Favorite')], default='A'),
        ),
    ]
