# Generated by Django 5.2.15 on 2026-07-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_participant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('F', 'Favorite'), ('R', 'Archived'), ('T', 'Trash')], default='A', max_length=1),
        ),
    ]
